SELECT 
  CC.COMPANY_CODE AS COMPANY_CODE, 
  CC.FOUNDER AS FOUNDER, 
  COUNT(DISTINCT EM.LEAD_MANAGER_CODE) AS LEAD_MANAGER_COUNT, 
  COUNT(DISTINCT EM.SENIOR_MANAGER_CODE) AS SENIOR_MANAGER_COUNT, 
  COUNT(DISTINCT EM.MANAGER_CODE) AS MANAGER_COUNT, 
  COUNT(DISTINCT EM.EMPLOYEE_CODE) AS EMPLOYEE_COUNT 
FROM 
  COMPANY CC
  JOIN EMPLOYEE EM ON EM.COMPANY_CODE = CC.COMPANY_CODE
GROUP BY
  CC.COMPANY_CODE, 
  CC.FOUNDER 
ORDER BY 
  COMPANY_CODE ASC;
